#!/usr/bin/env bash
# Adding new intent
if [ $# -lt 1 ] 
	then 
		echo "Usage: newintent <intent_name>"
		exit
fi 

intent_name=$1

templateFileName="botRequired.js"
templateFilePath="./templates/$templateFileName"

cp $templateFilePath ./intents
mv ./intents/$templateFileName ./intents/$intent_name".js"

cp $templateFilePath ./messages
mv ./messages/$templateFileName ./messages/$intent_name"Messages.js"

sed -i "" '/return {/i \
	\ \ \ \ const Message = require('"'"'../messages/'"$intent_name"'Messages'"'"')(bot);\
	\
    ' ./intents/$intent_name".js"

mkdir ./messages/$intent_name

echo $intent_name" intent created"

code ./intents/$intent_name".js"
